### PR TITLE
Update build-qemu.sh

### PR DESCRIPTION
**Pull request by CarlFK**
add some tips for testing

### CODE REVIEW

**Review by mithro — COMMENTED** [review]
You'll have these if you entered the environment. We should check for that.

Btw can you send this to the TimVideos repo rather than mine.

**Comment by CarlFK** [comment]
> You'll have these if you entered the environment. We should check for that.

If you point me to a "start here" I will start there and test.  right now I found 2 emails and one readme, it wasn't clear what I needed first.

> Btw can you send this to the TimVideos repo rather than mine.  

I clicked github's Edit and it forked whatever I was looking at.  I am guessing you posted the url to yours.  I have no idea how to switch it.

**Comment by mithro** [comment]
. scripts/enter-env.sh
<Set platform / target if not building for the default, just like when building gateware>
./scripts/build-qemu.sh

**Comment by mithro** [comment]
Updated instructions at https://github.com/timvideos/qemu-litex/blob/master/README.md

**Pull request closed without merging**
